### ISSUE TITLE
Wrong version in PIP, and new release required.

### ISSUE THREAD

**Issue by ur4t** [veripress/veripress#10]
Though version number from `python -m pip list` is 1.0.9, `python -m veripress --version` returns 1.0.6. And I checked files and found they are 1.0.6.

And the path problem is still there in release 1.0.9, so a new release is required.

**Comment by richardchien** [comment]
Thanks for your notice. Unfortunately I am too busy recently, and may not have time to handle this until 2 or more months later. I will keep this issue open in case I forget.

**Comment by richardchien** [comment]
fix in 1.0.11
